#                                                                         __
# .-----.-----.______.-----.----.-----.--.--.--.--.______.----.---.-.----|  |--.-----.
# |  _  |  _  |______|  _  |   _|  _  |_   _|  |  |______|  __|  _  |  __|     |  -__|
# |___  |_____|      |   __|__| |_____|__.__|___  |      |____|___._|____|__|__|_____|
# |_____|            |__|                   |_____|
#
# Copyright (c) 2020 Fabio Cicerchia. https://fabiocicerchia.it. MIT License
# Repo: https://github.com/fabiocicerchia/go-proxy-cache

version: '3.8'

services:
  go-proxy-cache:
    build:
      context: ..
      dockerfile: Dockerfile
      network: host
      args:
        BUILD_CMD: build-race
    command: ["go-proxy-cache", "-debug"]
    depends_on:
      - redis
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ./config.yml:/app/config.yml
      - ./server.key:/app/server.key
      - ./server.pem:/app/server.pem

  redis:
    image: redis:6.0.8-alpine3.12
    ports:
      - "6379:6379"
    sysctls:
      # WARNING: The TCP backlog setting of 511 cannot be enforced because
      # /proc/sys/net/core/somaxconn is set to the lower value of 128.
      net.core.somaxconn: 1024

  nginx:
    image: nginx:1.19.5-alpine
    restart: always
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./server.key:/server.key
      - ./server.pem:/server.pem
    ports:
      - "8880:80" # http
      - "8881:81" # ws
      - "8882:82" # wss
      - "8883:443" # https

  node:
    image: node:15.4.0-alpine3.10
    restart: always
    command: "npm start"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "9001:8081" # ws
      - "9002:8082" # wss
